---
- hosts:
  - home
  become: true
  roles:
  - install_kubectl

  pre_tasks:

  - debug: msg="{{ ansible_os_family }}"
  - name: (Debian)Update package cache if last run was more than 6 hours ago
    apt: update_cache=yes cache_valid_time={{ 60 * 60 * 6 }}
    when: ansible_os_family == "Debian"


