---
- name: Check if docker is already installed
  stat: path=/usr/bin/docker
  register: docker_exists

- name: Check if installation folder exists
  stat: path={{ INSTALL_DIR }}
  register: installation_folder_exists

- name: Create the application folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{ INSTALL_DIR }}"
  when:
    - installation_folder_exists.stat.exists == False

- name: Install docker
  shell: |
    apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    apt-get update

    apt-get install docker-ce docker-ce-cli containerd.io

  register: install_docker
  when: docker_exists.stat.exists == False
- debug: msg="{{ install_docker }}"

- name: Allow use docker as non-root user
  shell: usermod -aG docker {{ ansible_user }}
  when:
    - docker_exists.stat.exists == False
  register: allow_non_root
- debug: msg="{{ allow_non_root }}"

- name: Confirm docker version
  shell: docker --version
  register: docker_version
- debug: msg="{{ docker_version }}"

- name: Check if docker-compose is already installed
  stat: path=/usr/bin/docker-compose
  register: docker_compose_exists

- name: Confirm computer architecture
  shell: uname -m
  register: architecture
  when:
    - docker_compose_exists.stat.exists == False
- debug: msg="{{ architecture }}"

- name: Confirm computer os
  shell: uname -s
  register: os
  when:
    - docker_compose_exists.stat.exists == False
- debug: msg="{{ os }}"

- name: Get docker-compose
  get_url:
    url: "{{item.url}}"
    dest: "{{ INSTALL_DIR }}/docker-compose.sh"
    mode: "a+x"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
#    checksum: "{{item.checksum}}"
  register: install_docker_compose
  when:
    - docker_compose_exists.stat.exists == False
    - architecture.stdout is match(item.regex)
  with_items:
    - name: "X86"
      url: "https://github.com/docker/compose/releases/download/{{DOCKER_COMPOSE_X86_VERSION}}/docker-compose-{{os.stdout}}-{{architecture.stdout}}"
      regex: ".*x86_64.*"
#      checksum: "md5:215daec920746cf607aec5e8e1ac0c7a"
    - name: "ARM"
      url: "https://github.com/javabean/arm-compose/releases/download/{{DOCKER_COMPOSE_ARM_VERSION}}/docker-compose-Linux-armv7l"
      regex: ".*arm.*"
#      checksum: "md5:ea4815004b248e1c0c696be6b1dfea10"
- debug: msg="{{ install_docker_compose }}"

- name: Install docker-compose
  file:
    src: "{{ INSTALL_DIR }}/docker-compose.sh"
    dest: "/usr/bin/docker-compose"
    state: link
  when:
    - docker_compose_exists.stat.exists == False
  register: link_docker_compose
- debug: msg="{{ link_docker_compose }}"

- name: Confirm docker-compose version
  shell: "docker-compose --version"
  register: docker_compose_version
- debug: msg="{{ docker_compose_version }}"